```{r}
#variable declaration, quotation marks mean that the inner stuff is gonna be a string
message <- 'hello world!'
message
```
```{r}
#the return value of the type() function is gonna be the actual data type of a variable
typeof(message)
```
```{r}
new_msg <- 123
new_msg
```
```{r}
#just purely creating a variable with numbers will give us "double" type which refers to double precision floating number
typeof(new_msg)
```
```{r}
#declare integer type variable by adding "L" at the end
number <- 4L
typeof(number)
```
```{r}
#indexing in R is 1 based
string <- "one based indexing"
#substring function accept the string itself and than the desired starting and ending point of the string variable
substring(string,1,1)
```
```{r}
#indexing in R is 1 based
string <- "one based indexing"
#substring function accept the string itself and than the desired starting and ending point of the string variable
substring(string,1,5)
```
```{r}
#replace given characters within a string
gsub(" ","_",string)
```